- name: default
  type: postgres
  host: localhost
  database: test
  username: root
  password: root
  synchronize: false
  logging: false
  entities:
  - ./dist/entity/**/*.js
  cli:
    entitiesDir: entity
